## 2020. 04. 08.

### 코틀린 - 예외 처리와 관리(supervision)

이 장에서는 예외 처리와 예외 발생 시의 취소에 관해 다룬다. 취소된 코루틴이 지연 지점에서 [`CancellationException`][kt-coroutine-cencellation-exception]을 던지고 이는 코루틴 기계(machinery)에서 무시된다는 것을 알고 있다. 하지만 취소 도중에 예외가 발생하거나 동일한 코루틴의 여러 자식들이 예외를 던지면 어떤 일이 벌어질까?



#### 예외 전파

코루틴 빌더는 두 가지 형태가 있다. [`launch`][kt-coroutine-launch]와 [`actor`][kt-coroutine-actor]처럼 자동으로 예외를 전파하는 유형과, [`async`][kt-coroutine-async]와 [`produce`][kt-coroutine-produce]처럼 이를 사용자에게 노출하는 유형이다. 전자는 Java의 `Thread.uncaughtExceptionHandler`와 비슷하게 예외를 처리되지 않은 것으로 취급한다. 반면에 후자는 최종적인 예외의 처리를 [`await`][kt-coroutine-await]이나 [`receive`][kt-coroutine-receive] 등을 통해 사용자에게 맡긴다([`produce`][kt-coroutine-produce]과 [`receive`][kt-coroutine-receive]는 [채널][kt-channel]에서 다룬다).

[`GlobalScope`][kt-coroutine-global-scope]에서 코루틴을 생성하는 간단한 예시를 통해 알아보자:

```kotlin
import kotlinx.coroutines.*

fun main() = runBlocking {
    val job = GlobalScope.launch {
        println("Throwing exception from launch")
        throw IndexOutOfBoundsException() // Will be printed to the console by Thread.defaultUncaughtExceptionHandler
    }
    job.join()
    println("Joined failed job")
    val deferred = GlobalScope.async {
        println("Throwing exception from async")
        throw ArithmeticException() // Nothing is printed, relying on user to call await
    }
    try {
        deferred.await()
        println("Unreached")
    } catch (e: ArithmeticException) {
        println("Caught ArithmeticException")
    }
}
```

([디버그 옵션][kt-coroutine-debug-option]를 활성화한) 이 코드의 출력은 다음과 같다:

```
Throwing exception from launch
Exception in thread "DefaultDispatcher-worker-2 @coroutine#2" java.lang.IndexOutOfBoundsException
Joined failed job
Throwing exception from async
Caught ArithmeticException
```



[kt-coroutine-cencellation-exception]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-cancellation-exception/index.html
[Kt-coroutine-launch]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/launch.html
[kt-coroutine-actor]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/actor.html
[kt-coroutine-async]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/async.html
[kt-coroutine-produce]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/produce.html
[kt-coroutine-await]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-deferred/await.html
[kt-coroutine-receive]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.channels/-receive-channel/receive.html
[kt-channel]: https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/channels.md
[kt-coroutine-global-scope]: https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-global-scope/index.html
[kt-coroutine-debug-option]: https://github.com/Kotlin/kotlinx.coroutines/blob/master/docs/coroutine-context-and-dispatchers.md#debugging-coroutines-and-threads